# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\"\x07\n\x05\x45mpty\"\x1c\n\x0cScheduleDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\",\n\x0cScheduleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"-\n\tSchedules\x12 \n\tschedules\x18\x01 \x03(\x0b\x32\r.ScheduleData\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x16GetDatesByMovieRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\"\x1a\n\tDatesList\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t2\x88\x02\n\x08Schedule\x12\'\n\x0fGetAllSchedules\x12\x06.Empty\x1a\n.Schedules\"\x00\x12\x33\n\x11GetScheduleByDate\x12\r.ScheduleDate\x1a\r.ScheduleData\"\x00\x12\x38\n\x0fGetDatesByMovie\x12\x17.GetDatesByMovieRequest\x1a\n.DatesList\"\x00\x12\x30\n\x0e\x43reateSchedule\x12\r.ScheduleData\x1a\r.ScheduleData\"\x00\x12\x32\n\x0e\x44\x65leteSchedule\x12\r.ScheduleDate\x1a\x0f.DeleteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_SCHEDULEDATE']._serialized_start=27
  _globals['_SCHEDULEDATE']._serialized_end=55
  _globals['_SCHEDULEDATA']._serialized_start=57
  _globals['_SCHEDULEDATA']._serialized_end=101
  _globals['_SCHEDULES']._serialized_start=103
  _globals['_SCHEDULES']._serialized_end=148
  _globals['_DELETERESPONSE']._serialized_start=150
  _globals['_DELETERESPONSE']._serialized_end=200
  _globals['_GETDATESBYMOVIEREQUEST']._serialized_start=202
  _globals['_GETDATESBYMOVIEREQUEST']._serialized_end=244
  _globals['_DATESLIST']._serialized_start=246
  _globals['_DATESLIST']._serialized_end=272
  _globals['_SCHEDULE']._serialized_start=275
  _globals['_SCHEDULE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
